language: python

sudo: false

python:
  - "2.7"
  - "3.6"
  - "pypy"

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOXENV=lnx-Django17
  - TOXENV=lnx-Django18
  - TOXENV=lnx-Django111
  - TOXENV=lnx-Django20

install:
  - pip install 'tox>=2' -U

script:
  - tox
