language: python

sudo: false

python:
  - "2.7"
  - "3.6"
  - "pypy"

cache: pip

python:
    - "2.7"
    - "3.4"
    - "3.5"

sudo: false

env:
    - DJANGO=1.8
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=master

matrix:
    fast_finish: true
    include:
      - { python: "3.6", env: DJANGO=master }
      - { python: "3.6", env: DJANGO=1.11 }
      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }

    exclude:
      - { python: "2.7", env: DJANGO=master }
      - { python: "2.7", env: DJANGO=2.0 }
      - { python: "2.7", env: DJANGO=2.1 }
      - { python: "3.4", env: DJANGO=master }
      - { python: "3.4", env: DJANGO=2.1 }

    allow_failures:
      - env: DJANGO=master
      - env: DJANGO=2.1

install:
    - pip install tox tox-travis

script:
    - tox


install:
  - pip install tox-travis -U

script:
  - tox
